// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhDwLYuhoxLPgbqkCuqTFTdWf0NcIyS5M',
    appId: '1:17648285998:web:238435c422d46a628e22bf',
    messagingSenderId: '17648285998',
    projectId: 'videotecadb-a999a',
    authDomain: 'videotecadb-a999a.firebaseapp.com',
    storageBucket: 'videotecadb-a999a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK7KNHFjy3Dr2oJvSOPR4rRgMn-SOprHw',
    appId: '1:17648285998:android:c444f0aa4d4bfe158e22bf',
    messagingSenderId: '17648285998',
    projectId: 'videotecadb-a999a',
    storageBucket: 'videotecadb-a999a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHqPXwISe4GK-yWg68viM6ll00ZInnvo0',
    appId: '1:17648285998:ios:a99635f3fbc802558e22bf',
    messagingSenderId: '17648285998',
    projectId: 'videotecadb-a999a',
    storageBucket: 'videotecadb-a999a.firebasestorage.app',
    iosBundleId: 'com.example.proyectoVideoteca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHqPXwISe4GK-yWg68viM6ll00ZInnvo0',
    appId: '1:17648285998:ios:a99635f3fbc802558e22bf',
    messagingSenderId: '17648285998',
    projectId: 'videotecadb-a999a',
    storageBucket: 'videotecadb-a999a.firebasestorage.app',
    iosBundleId: 'com.example.proyectoVideoteca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhDwLYuhoxLPgbqkCuqTFTdWf0NcIyS5M',
    appId: '1:17648285998:web:160741f4d9f42eee8e22bf',
    messagingSenderId: '17648285998',
    projectId: 'videotecadb-a999a',
    authDomain: 'videotecadb-a999a.firebaseapp.com',
    storageBucket: 'videotecadb-a999a.firebasestorage.app',
  );
}
